// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/

import java.util.ArrayList;

/**
 * 
 */
public class Controller {


	private ArrayList<Store> storeList;
	/**
	 * 
	 */
	public void getStores() {
	}

	/**
	 * 
	 */
	public void orderToStore() {
	}

	/**
	 * 
	 */
	public void orderComplete() {
	}

	public static void main(String[] args)
	{
		Manager manager = new Manager();
		manager.Name = "Mike";
		Driver driver = new Driver();
		driver.Name = "Mary";
		Cook cook = new Cook();
		cook.Name = "Chris";
		Accountant accountant = new Accountant();
		accountant.Name = "Sarah";
		Store store = new Store();
		store.employeeList.add(manager);
		store.employeeList.add(cook);
		store.employeeList.add(driver);
		store.employeeList.add(accountant);


		System.out.println("Employees: ");
		System.out.println(store.toString());

		System.out.println("Current Menu: ");
		View view = new View();
		view.viewMenu();

	}
}

