// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
/**
 * 
 */
public class Cook extends Employee {

	public void cookFood() {
		System.out.println("Food is Cooked");
	}
}
