// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
/**
 *
 */
public class Driver extends Employee {

    public void deliverFood() {
        System.out.println("Food delivered to: ");
    }
}
