// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
/**
 * 
 */
public class Employee {
	/**
	 *
	 */
	public String Name;
	/**
	 *
	 */
	private String Pay;
	/**
	 * 
	 */
	private String Schedule;

}
