// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------




/************************************************************/
/**
 * 
 */
public class Manager extends Employee
 {
	public void editMenu() {
		System.out.println("Menu Edited");
	}
	/**
	 * 
	 */
	public void editSchedule() {
		System.out.println("Schedule Changed");
	}
}
