// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/

import java.util.ArrayList;

/**
 * 
 */
class Order {
	private ArrayList<Integer> foodList;
	/**
	 * 
	 */
	private String Location;
	/**
	 * 
	 */
	private String Type;
	/**
	 * 
	 */
	private int Number;
	/**
	 * 
	 */
	private Boolean isComplete;
	/**
	 * 
	 */
	public Store store;
}
