// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/

import java.util.ArrayList;



public class Store {
	public Store() {
	}

	/**
	 * 
	 */
	private ArrayList<String> Menu;
	/**
	 * 
	 */
	private ArrayList<Order> OrderList;
	/**
	 * 
	 */
	private String Location;
	/**
	 * 
	 */
	private String Hours;
	/**
	 * 
	 */
	private String DeliveryRules;
	/**
	 * 
	 */
	private ArrayList<String> feedbackList;
	/**
	 * 
	 */
	public ArrayList<Employee> employeeList = new ArrayList<Employee>();
	/**
	 * 
	 */
	public ArrayList<Order> order;

	/**
	 * 
	 */
	public void fulfillOrder() {
		System.out.println("Order is being Prepared");
	}



	@Override
	public String toString() {

		for (int i = 0; i < employeeList.size();i++) {
			System.out.println(employeeList.get(i).Name);
		}

		return " ";

	}
}
