// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------



/************************************************************/

import java.util.ArrayList;

/**
 * 
 */
public class View {
	private String OptionsPrompt;
	/**
	 * 
	 */
	private int StoreSelection;
	/**
	 * 
	 */
	private int orderType;
	/**
	 * 
	 */
	private String Location;
	/**
	 * 
	 */
	private ArrayList<Integer> foodList;

	/**
	 * 
	 */
	public static void viewMenu() {
		System.out.println("1 - Pizza \n2 - California Roll\n3 - Cacio e Pepe");
	}

	/**
	 * 
	 */
	public void placeOrder() {
	}

	/**
	 * 
	 */
	public void sendFeedBack() {
	}
}
